'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import {
    TrendingUp,
    Users,
    DollarSign,
    CalendarDays,
    Clock,
    Star,
    Activity,
    ArrowUpRight,
    ArrowDownRight,
    Filter,
    Calendar,
    Package,
    FileText,
    ShoppingCart,
    AlertTriangle,
    Layers,
    BarChart3,
    Sliders,
} from 'lucide-react';
import {
    ResponsiveContainer,
    AreaChart,
    Area,
    CartesianGrid,
    XAxis,
    YAxis,
    BarChart,
    Bar,
    Tooltip,
} from 'recharts';
import { Button, Select } from '@/components/ui';

// --- Real Data for All Categories ---

const getRevenueData = () => ({
    title: 'Revenue Overview',
    kpis: [
        { label: 'Total Revenue', value: '158,000 EGP', change: '+12%', trend: 'up', icon: DollarSign, color: 'primary' },
        { label: 'Avg Transaction', value: '420 EGP', change: '+5%', trend: 'up', icon: Activity, color: 'info' },
        { label: 'Refunds', value: '2,400 EGP', change: '-2%', trend: 'down', icon: TrendingUp, color: 'error' },
        { label: 'Net Profit', value: '45,000 EGP', change: '+8%', trend: 'up', icon: DollarSign, color: 'success' },
    ],
    chart: {
        title: 'Monthly Revenue Trend',
        type: 'area',
        data: [
            { name: 'Sep', value: 42000 }, { name: 'Oct', value: 48000 },
            { name: 'Nov', value: 52000 }, { name: 'Dec', value: 61000 },
            { name: 'Jan', value: 55000 }, { name: 'Feb', value: 58000 },
        ]
    },
    reports: [
        { title: 'Daily Revenue', href: '/reports/revenue/daily-revenue', desc: 'Breakdown of revenue by day.' },
        { title: 'Payment Methods', href: '/reports/revenue/payment-methods', desc: 'Cash vs Card vs Transfer analysis.' },
        { title: 'Service Revenue', href: '/reports/revenue/service-revenue', desc: 'Revenue generated by each service.' },
        { title: 'Tax Report', href: '/reports/revenue/tax-report', desc: 'VAT and tax collected.' },
    ]
});

const getBookingsData = () => ({
    title: 'Bookings Overview',
    kpis: [
        { label: 'Total Bookings', value: '842', change: '+15%', trend: 'up', icon: CalendarDays, color: 'primary' },
        { label: 'Completed', value: '780', change: '+18%', trend: 'up', icon: CalendarDays, color: 'success' },
        { label: 'Cancelled', value: '42', change: '-5%', trend: 'down', icon: Activity, color: 'error' },
        { label: 'No Show', value: '20', change: '0%', trend: 'neutral', icon: Users, color: 'warning' },
    ],
    chart: {
        title: 'Weekly Booking Volume',
        type: 'bar',
        data: [
            { name: 'Mon', value: 120 }, { name: 'Tue', value: 132 },
            { name: 'Wed', value: 101 }, { name: 'Thu', value: 134 },
            { name: 'Fri', value: 190 }, { name: 'Sat', value: 230 },
            { name: 'Sun', value: 100 },
        ]
    },
    reports: [
        { title: 'Booking History', href: '/reports/bookings/history', desc: 'Full log of all appointments.' },
        { title: 'Cancellations', href: '/reports/bookings/cancellations', desc: 'Analysis of cancelled appointments.' },
        { title: 'Utilization', href: '/reports/bookings/utilization', desc: 'Room and resource usage rates.' },
        { title: 'Online vs Walk-in', href: '/reports/bookings/sources', desc: 'Booking source comparison.' },
    ]
});

const getClientsData = () => ({
    title: 'Client Analytics',
    kpis: [
        { label: 'Total Clients', value: '1,240', change: '+8%', trend: 'up', icon: Users, color: 'primary' },
        { label: 'New Clients', value: '85', change: '+12%', trend: 'up', icon: Users, color: 'success' },
        { label: 'Returning', value: '78%', change: '+2%', trend: 'up', icon: Activity, color: 'info' },
        { label: 'Lost Clients', value: '12', change: '-5%', trend: 'down', icon: Users, color: 'error' },
    ],
    chart: {
        title: 'New vs Returning Clients',
        type: 'area',
        data: [
            { name: 'Sep', value: 120 }, { name: 'Oct', value: 132 },
            { name: 'Nov', value: 101 }, { name: 'Dec', value: 134 },
            { name: 'Jan', value: 90 }, { name: 'Feb', value: 230 },
        ]
    },
    reports: [
        { title: 'Top Spenders', href: '/reports/clients/top-spenders', desc: 'Clients with highest lifetime value.' },
        { title: 'Retention Rate', href: '/reports/clients/retention', desc: 'Client return rate analysis.' },
        { title: 'Client Feedback', href: '/reports/clients/feedback', desc: 'Ratings and reviews summary.' },
        { title: 'Demographics', href: '/reports/clients/demographics', desc: 'Age and location breakdown.' },
    ]
});

const getEmployeesData = () => ({
    title: 'Staff Performance',
    kpis: [
        { label: 'Active Staff', value: '18', change: '0%', trend: 'neutral', icon: Users, color: 'primary' },
        { label: 'Avg Revenue', value: '12.5K', change: '+5%', trend: 'up', icon: DollarSign, color: 'success' },
        { label: 'Avg Rating', value: '4.8', change: '+0.1', trend: 'up', icon: Star, color: 'warning' },
        { label: 'Utilization', value: '85%', change: '+2%', trend: 'up', icon: Clock, color: 'info' },
    ],
    chart: {
        title: 'Revenue per Employee (Top 5)',
        type: 'bar',
        data: [
            { name: 'Sara', value: 24000 }, { name: 'Nora', value: 18000 },
            { name: 'Mona', value: 15000 }, { name: 'Layla', value: 12000 },
            { name: 'Reem', value: 9000 },
        ]
    },
    reports: [
        { title: 'Commissions', href: '/reports/employees/commissions', desc: 'Calculated commissions for payroll.' },
        { title: 'Employee Sales', href: '/reports/employees/sales', desc: 'Detailed sales performance by staff.' },
        { title: 'Attendance', href: '/reports/employees/attendance', desc: 'Work hours and punctuality.' },
        { title: 'Service Quality', href: '/reports/employees/quality', desc: 'Client ratings per employee.' },
    ]
});

const getServicesData = () => ({
    title: 'Services Analytics',
    kpis: [
        { label: 'Active Services', value: '42', change: '+3', trend: 'up', icon: Package, color: 'primary' },
        { label: 'Top Service', value: 'HydraFacial', change: '85 bookings', trend: 'up', icon: Star, color: 'success' },
        { label: 'Avg Revenue/Service', value: '3,760 EGP', change: '+6%', trend: 'up', icon: DollarSign, color: 'info' },
        { label: 'Low Demand', value: '5', change: '-2', trend: 'down', icon: AlertTriangle, color: 'warning' },
    ],
    chart: {
        title: 'Top 6 Services by Revenue',
        type: 'bar',
        data: [
            { name: 'HydraFacial', value: 14000 },
            { name: 'Hair Cut', value: 12750 },
            { name: 'Massage', value: 11500 },
            { name: 'Manicure', value: 9750 },
            { name: 'Laser', value: 8200 },
            { name: 'Pedicure', value: 6400 },
        ]
    },
    reports: [
        { title: 'Service Popularity', href: '/reports/services/popularity', desc: 'Most and least booked services.' },
        { title: 'Revenue per Service', href: '/reports/services/revenue', desc: 'Revenue breakdown by service type.' },
        { title: 'Service Duration', href: '/reports/services/duration', desc: 'Average completion time analysis.' },
        { title: 'Category Breakdown', href: '/reports/services/categories', desc: 'Performance grouped by category.' },
    ]
});

const getInventoryData = () => ({
    title: 'Inventory Dashboard',
    kpis: [
        { label: 'Total Products', value: '134', change: '+8', trend: 'up', icon: ShoppingCart, color: 'primary' },
        { label: 'Stock Value', value: '42,500 EGP', change: '+4%', trend: 'up', icon: DollarSign, color: 'success' },
        { label: 'Low Stock Items', value: '12', change: '+3', trend: 'up', icon: AlertTriangle, color: 'error' },
        { label: 'Monthly Usage', value: '8,200 EGP', change: '+7%', trend: 'up', icon: Activity, color: 'info' },
    ],
    chart: {
        title: 'Monthly Product Consumption',
        type: 'area',
        data: [
            { name: 'Sep', value: 6800 }, { name: 'Oct', value: 7200 },
            { name: 'Nov', value: 7500 }, { name: 'Dec', value: 8900 },
            { name: 'Jan', value: 7800 }, { name: 'Feb', value: 8200 },
        ]
    },
    reports: [
        { title: 'Stock Levels', href: '/reports/inventory/stock-levels', desc: 'Current stock with reorder alerts.' },
        { title: 'Product Usage', href: '/reports/inventory/usage', desc: 'Consumption per service and employee.' },
        { title: 'Purchase History', href: '/reports/inventory/purchases', desc: 'Recent orders and supplier spend.' },
        { title: 'Waste & Expiry', href: '/reports/inventory/waste', desc: 'Expired or wasted product tracking.' },
    ]
});

const getCustomData = () => ({
    title: 'Custom Reports',
    kpis: [
        { label: 'Saved Reports', value: '7', change: '+2', trend: 'up', icon: FileText, color: 'primary' },
        { label: 'Scheduled', value: '3', change: '0', trend: 'neutral', icon: Clock, color: 'info' },
        { label: 'Last Generated', value: 'Today', change: '', trend: 'neutral', icon: Activity, color: 'success' },
        { label: 'Data Sources', value: '5', change: '', trend: 'neutral', icon: Layers, color: 'warning' },
    ],
    chart: {
        title: 'Report Generation Frequency',
        type: 'bar',
        data: [
            { name: 'Revenue', value: 15 }, { name: 'Bookings', value: 12 },
            { name: 'Clients', value: 8 }, { name: 'Employees', value: 6 },
            { name: 'Services', value: 4 }, { name: 'Inventory', value: 3 },
        ]
    },
    reports: [
        { title: 'Revenue vs Bookings', href: '/reports/custom/revenue-bookings', desc: 'Cross-metric comparison of revenue and bookings.' },
        { title: 'Employee Efficiency', href: '/reports/custom/employee-efficiency', desc: 'Revenue per hour per employee analysis.' },
        { title: 'Client Lifetime Value', href: '/reports/custom/client-ltv', desc: 'Projected lifetime value by segment.' },
        { title: 'Monthly Summary', href: '/reports/custom/monthly-summary', desc: 'Executive summary for stakeholders.' },
    ]
});

import styles from '../reports.module.css';

export default function ReportCategoryPage({ params }: { params: Promise<{ category: string }> }) {
    const { category } = React.use(params);
    const [dateRange, setDateRange] = useState('30d');

    let data;
    switch (category) {
        case 'revenue': data = getRevenueData(); break;
        case 'bookings': data = getBookingsData(); break;
        case 'clients': data = getClientsData(); break;
        case 'employees': data = getEmployeesData(); break;
        case 'services': data = getServicesData(); break;
        case 'inventory': data = getInventoryData(); break;
        case 'custom': data = getCustomData(); break;
        default: data = getServicesData();
    }

    const dateLabel = dateRange === '7d' ? 'Last 7 Days' : dateRange === '30d' ? 'Last 30 Days' : 'Last Quarter';

    return (
        <div className={styles.categoryPage}>
            {/* Filters */}
            <div className={styles.categoryHeader}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
                    <Calendar size={16} color="var(--text-tertiary)" />
                    <Select
                        value={dateRange}
                        onChange={(e: React.ChangeEvent<HTMLSelectElement>) => setDateRange(e.target.value)}
                        options={[
                            { value: '7d', label: 'Last 7 Days' },
                            { value: '30d', label: 'Last 30 Days' },
                            { value: '90d', label: 'Last Quarter' },
                        ]}
                        style={{ width: 150 }}
                    />
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-2)' }}>
                    <Filter size={16} color="var(--text-tertiary)" />
                    <Select
                        options={[
                            { value: 'all', label: 'All Branches' },
                            { value: 'main', label: 'Main Branch' },
                            { value: 'branch2', label: 'Heliopolis Branch' },
                        ]}
                        style={{ width: 160 }}
                    />
                </div>
            </div>

            <h2 className={styles.categoryTitle}>{data.title}</h2>

            <div className={styles.kpiGrid}>
                {data.kpis.map((kpi, i) => (
                    <div key={i} className={styles.kpiCard}>
                        <div
                            className={styles.kpiIconWrapper}
                            style={{
                                background: `var(--color-${kpi.color}-50, #f3f4f6)`,
                                color: `var(--color-${kpi.color}, #6b7280)`
                            }}
                        >
                            <kpi.icon size={24} />
                        </div>
                        <div>
                            <div className={styles.kpiLabel}>{kpi.label}</div>
                            <div className={styles.kpiValue}>{kpi.value}</div>
                            {kpi.change && (
                                <div className={`${styles.kpiTrendWrapper} ${kpi.trend === 'up' ? styles.kpiTrendUp :
                                    kpi.trend === 'down' ? styles.kpiTrendDown :
                                        styles.kpiTrendNeutral
                                    }`}>
                                    {kpi.trend === 'up' && <ArrowUpRight size={12} />}
                                    {kpi.trend === 'down' && <ArrowDownRight size={12} />}
                                    {kpi.change} from last period
                                </div>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            {/* Main Chart */}
            <div className={styles.chartCard}>
                <h3 className={styles.chartTitle}>{data.chart.title}</h3>
                <div className={styles.chartContainer}>
                    <ResponsiveContainer width="100%" height="100%">
                        {data.chart.type === 'bar' ? (
                            <BarChart data={data.chart.data}>
                                <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                                <XAxis dataKey="name" stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} dy={10} />
                                <YAxis stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} />
                                <Tooltip cursor={{ fill: 'var(--bg-secondary)' }} contentStyle={{ borderRadius: 8, border: 'none', boxShadow: 'var(--shadow-lg)' }} />
                                <Bar dataKey="value" fill="var(--color-primary-500)" radius={[4, 4, 0, 0]} barSize={40} />
                            </BarChart>
                        ) : (
                            <AreaChart data={data.chart.data}>
                                <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                                <XAxis dataKey="name" stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} dy={10} />
                                <YAxis stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} />
                                <Tooltip contentStyle={{ borderRadius: 8, border: 'none', boxShadow: 'var(--shadow-lg)' }} />
                                <Area type="monotone" dataKey="value" stroke="var(--color-primary-500)" fill="var(--color-primary-100)" strokeWidth={3} />
                            </AreaChart>
                        )}
                    </ResponsiveContainer>
                </div>
            </div>

            {/* Detailed Reports Grid */}
            <div>
                <h3 className={styles.chartTitle} style={{ marginBottom: 'var(--space-4)' }}>Detailed Reports</h3>
                <div className={styles.reportsGrid}>
                    {data.reports.map((report, i) => (
                        <Link key={i} href={report.href} className={styles.reportCard}>
                            <div className={styles.reportCardHeader}>
                                <div className={styles.reportCardTitle}>{report.title}</div>
                                <ArrowUpRight size={16} color="var(--text-tertiary)" />
                            </div>
                            <div className={styles.reportCardDesc}>{report.desc}</div>
                        </Link>
                    ))}
                </div>
            </div>
        </div>
    );
}
