'use client';

import React from 'react';
import Link from 'next/link';
import {
    TrendingUp,
    Users,
    DollarSign,
    CalendarDays,
    Clock,
    Star,
    Activity,
    ArrowUpRight,
    ArrowDownRight,
    Filter
} from 'lucide-react';
import {
    ResponsiveContainer,
    AreaChart,
    Area,
    CartesianGrid,
    XAxis,
    YAxis,
    BarChart,
    Bar,
    Tooltip,
} from 'recharts';
import { Button, Select } from '@/components/ui';

// --- Mock Data Generators (Unchanged) ---
// I am keeping the data generators exactly as they were in the previous file.

const getRevenueData = () => ({
    title: 'Revenue Overview',
    kpis: [
        { label: 'Total Revenue', value: '158,000 EGP', change: '+12%', trend: 'up', icon: DollarSign, color: 'primary' },
        { label: 'Avg Transaction', value: '420 EGP', change: '+5%', trend: 'up', icon: Activity, color: 'info' },
        { label: 'Refunds', value: '2,400 EGP', change: '-2%', trend: 'down', icon: TrendingUp, color: 'error' },
        { label: 'Net Profit', value: '45,000 EGP', change: '+8%', trend: 'up', icon: DollarSign, color: 'success' },
    ],
    chart: {
        title: 'Monthly Revenue Trend',
        type: 'area',
        data: [
            { name: 'Sep', value: 42000 }, { name: 'Oct', value: 48000 },
            { name: 'Nov', value: 52000 }, { name: 'Dec', value: 61000 },
            { name: 'Jan', value: 55000 }, { name: 'Feb', value: 58000 },
        ]
    },
    reports: [
        { title: 'Daily Revenue', href: '/reports/sales/daily-revenue', desc: 'Breakdown of revenue by day.' },
        { title: 'Payment Methods', href: '/reports/sales/payment-methods', desc: 'Cash vs Card vs Transfer analysis.' },
        { title: 'Service Revenue', href: '/reports/sales/service-revenue', desc: 'Revenue generated by each service.' },
        { title: 'Tax Report', href: '/reports/sales/tax-report', desc: 'VAT and tax collected.' },
    ]
});

const getBookingsData = () => ({
    title: 'Bookings Overview',
    kpis: [
        { label: 'Total Bookings', value: '842', change: '+15%', trend: 'up', icon: CalendarDays, color: 'primary' },
        { label: 'Completed', value: '780', change: '+18%', trend: 'up', icon: CalendarDays, color: 'success' },
        { label: 'Cancelled', value: '42', change: '-5%', trend: 'down', icon: Activity, color: 'error' },
        { label: 'No Show', value: '20', change: '0%', trend: 'neutral', icon: Users, color: 'warning' },
    ],
    chart: {
        title: 'Weekly Booking Volume',
        type: 'bar',
        data: [
            { name: 'Mon', value: 120 }, { name: 'Tue', value: 132 },
            { name: 'Wed', value: 101 }, { name: 'Thu', value: 134 },
            { name: 'Fri', value: 190 }, { name: 'Sat', value: 230 },
            { name: 'Sun', value: 100 },
        ]
    },
    reports: [
        { title: 'Booking History', href: '/reports/bookings/history', desc: 'Full log of all appointments.' },
        { title: 'Cancellations', href: '/reports/bookings/cancellations', desc: 'Analysis of cancelled appointments.' },
        { title: 'Utilization', href: '/reports/bookings/utilization', desc: 'Room and resource usage rates.' },
        { title: 'Online vs Walk-in', href: '/reports/bookings/sources', desc: 'Booking source comparison.' },
    ]
});

const getClientsData = () => ({
    title: 'Client Analytics',
    kpis: [
        { label: 'Total Clients', value: '1,240', change: '+8%', trend: 'up', icon: Users, color: 'primary' },
        { label: 'New Clients', value: '85', change: '+12%', trend: 'up', icon: Users, color: 'success' },
        { label: 'Returning', value: '78%', change: '+2%', trend: 'up', icon: Activity, color: 'info' },
        { label: 'Lost Clients', value: '12', change: '-5%', trend: 'down', icon: Users, color: 'error' },
    ],
    chart: {
        title: 'New vs Returning Clients',
        type: 'area',
        data: [
            { name: 'Sep', value: 120 }, { name: 'Oct', value: 132 },
            { name: 'Nov', value: 101 }, { name: 'Dec', value: 134 },
            { name: 'Jan', value: 90 }, { name: 'Feb', value: 230 },
        ]
    },
    reports: [
        { title: 'Top Spenders', href: '/reports/clients/top-spenders', desc: 'Clients with highest lifetime value.' },
        { title: 'Retention Rate', href: '/reports/clients/retention', desc: 'Client return rate analysis.' },
        { title: 'Client Feedback', href: '/reports/clients/feedback', desc: 'Ratings and reviews summary.' },
        { title: 'Demographics', href: '/reports/clients/demographics', desc: 'Age and location breakdown.' },
    ]
});

const getEmployeesData = () => ({
    title: 'Staff Performance',
    kpis: [
        { label: 'Active Staff', value: '18', change: '0%', trend: 'neutral', icon: Users, color: 'primary' },
        { label: 'Avg Revenue', value: '12.5K', change: '+5%', trend: 'up', icon: DollarSign, color: 'success' },
        { label: 'Avg Rating', value: '4.8', change: '+0.1', trend: 'up', icon: Star, color: 'warning' },
        { label: 'Utilization', value: '85%', change: '+2%', trend: 'up', icon: Clock, color: 'info' },
    ],
    chart: {
        title: 'Revenue per Employee (Top 5)',
        type: 'bar',
        data: [
            { name: 'Sara', value: 24000 }, { name: 'Nora', value: 18000 },
            { name: 'Mona', value: 15000 }, { name: 'Layla', value: 12000 },
            { name: 'Reem', value: 9000 },
        ]
    },
    reports: [
        { title: 'Commissions', href: '/reports/employees/commissions', desc: 'Calculated commissions for payroll.' },
        { title: 'Employee Sales', href: '/reports/employees/sales', desc: 'Detailed sales performance by staff.' },
        { title: 'Attendance', href: '/reports/employees/attendance', desc: 'Work hours and punctuality.' },
        { title: 'Service Quality', href: '/reports/employees/quality', desc: 'Client ratings per employee.' },
    ]
});

const getGenericData = (category: string) => ({
    title: `${category.charAt(0).toUpperCase() + category.slice(1)} Dashboard`,
    kpis: [
        { label: 'Metric A', value: '1,234', change: '+10%', trend: 'up', icon: Activity, color: 'primary' },
        { label: 'Metric B', value: '85%', change: '+5%', trend: 'up', icon: Activity, color: 'success' },
        { label: 'Metric C', value: '420', change: '-2%', trend: 'down', icon: Activity, color: 'info' },
        { label: 'Metric D', value: '12', change: '0%', trend: 'neutral', icon: Activity, color: 'warning' },
    ],
    chart: {
        title: 'Activity Trends',
        type: 'area',
        data: [
            { name: 'Mon', value: 400 }, { name: 'Tue', value: 300 },
            { name: 'Wed', value: 550 }, { name: 'Thu', value: 450 },
            { name: 'Fri', value: 600 }, { name: 'Sat', value: 700 },
            { name: 'Sun', value: 200 },
        ]
    },
    reports: [
        { title: 'General Report', href: `/reports/${category}/general`, desc: 'Overview report.' },
        { title: 'Detailed Analysis', href: `/reports/${category}/detailed`, desc: 'Deep dive into data.' },
        { title: 'Export Data', href: `/reports/${category}/export`, desc: 'Download raw data.' },
    ]
});

// --- Components ---

import styles from '../reports.module.css';

export default function ReportCategoryPage({ params }: { params: Promise<{ category: string }> }) {
    const { category } = React.use(params);

    let data;
    switch (category) {
        case 'revenue': data = getRevenueData(); break;
        case 'bookings': data = getBookingsData(); break;
        case 'clients': data = getClientsData(); break;
        case 'employees': data = getEmployeesData(); break;
        default: data = getGenericData(category);
    }

    return (
        <div className={styles.categoryPage}>
            <div className={styles.categoryHeader}>
                <Select options={[{ value: '30d', label: 'Last 30 Days' }, { value: '90d', label: 'Last Quarter' }]} style={{ width: 140 }} />
                <Button variant="outline"><Filter size={16} /> Filter</Button>
            </div>

            <h2 className={styles.categoryTitle}>{data.title}</h2>

            <div className={styles.kpiGrid}>
                {data.kpis.map((kpi, i) => (
                    <div key={i} className={styles.kpiCard}>
                        <div
                            className={styles.kpiIconWrapper}
                            style={{
                                background: `var(--color-${kpi.color}-50)`,
                                color: `var(--color-${kpi.color})`
                            }}
                        >
                            <kpi.icon size={24} />
                        </div>
                        <div>
                            <div className={styles.kpiLabel}>{kpi.label}</div>
                            <div className={styles.kpiValue}>{kpi.value}</div>
                            <div className={`${styles.kpiTrendWrapper} ${kpi.trend === 'up' ? styles.kpiTrendUp :
                                kpi.trend === 'down' ? styles.kpiTrendDown :
                                    styles.kpiTrendNeutral
                                }`}>
                                {kpi.trend === 'up' && <ArrowUpRight size={12} />}
                                {kpi.trend === 'down' && <ArrowDownRight size={12} />}
                                {kpi.change} from last period
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Main Chart */}
            <div className={styles.chartCard}>
                <h3 className={styles.chartTitle}>{data.chart.title}</h3>
                <div className={styles.chartContainer}>
                    <ResponsiveContainer width="100%" height="100%">
                        {data.chart.type === 'bar' ? (
                            <BarChart data={data.chart.data}>
                                <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                                <XAxis dataKey="name" stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} dy={10} />
                                <YAxis stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} />
                                <Tooltip cursor={{ fill: 'var(--bg-secondary)' }} contentStyle={{ borderRadius: 8, border: 'none', boxShadow: 'var(--shadow-lg)' }} />
                                <Bar dataKey="value" fill="var(--color-primary-500)" radius={[4, 4, 0, 0]} barSize={40} />
                            </BarChart>
                        ) : (
                            <AreaChart data={data.chart.data}>
                                <CartesianGrid strokeDasharray="3 3" stroke="var(--border-color)" vertical={false} />
                                <XAxis dataKey="name" stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} dy={10} />
                                <YAxis stroke="var(--text-tertiary)" fontSize={12} tickLine={false} axisLine={false} />
                                <Tooltip contentStyle={{ borderRadius: 8, border: 'none', boxShadow: 'var(--shadow-lg)' }} />
                                <Area type="monotone" dataKey="value" stroke="var(--color-primary-500)" fill="var(--color-primary-100)" strokeWidth={3} />
                            </AreaChart>
                        )}
                    </ResponsiveContainer>
                </div>
            </div>

            {/* Detailed Reports Grid */}
            <div>
                <h3 className={styles.chartTitle} style={{ marginBottom: 'var(--space-4)' }}>Detailed Reports</h3>
                <div className={styles.reportsGrid}>
                    {data.reports.map((report, i) => (
                        <Link key={i} href={report.href} className={styles.reportCard}>
                            <div className={styles.reportCardHeader}>
                                <div className={styles.reportCardTitle}>{report.title}</div>
                                <ArrowUpRight size={16} color="var(--text-tertiary)" />
                            </div>
                            <div className={styles.reportCardDesc}>{report.desc}</div>
                        </Link>
                    ))}
                </div>
            </div>
        </div>
    );
}
