import React from 'react';

// ─── Design tokens ───────────────────────────────────────────────────────────

export const s: Record<string, React.CSSProperties> = {
    // Layout
    page: { display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' },
    header: { display: 'flex', alignItems: 'center', gap: 'var(--space-4)' },
    h1: { fontSize: 'var(--text-2xl)', fontWeight: 'var(--font-bold)' },
    formGrid: { display: 'grid', gridTemplateColumns: '1fr 360px', gap: 'var(--space-6)', alignItems: 'start' },
    col: { display: 'flex', flexDirection: 'column', gap: 'var(--space-5)' },
    row2: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 'var(--space-4)' },
    row3: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 'var(--space-4)' },
    // Cards
    card: {
        background: 'var(--bg-primary)',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--radius-xl)',
        padding: 'var(--space-6)',
    },
    cardConflict: {
        background: 'var(--bg-primary)',
        border: '1px solid var(--color-warning)',
        borderRadius: 'var(--radius-xl)',
        padding: 'var(--space-6)',
    },
    cardTitle: {
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-2)',
        fontSize: 'var(--text-lg)',
        fontWeight: 'var(--font-semibold)',
        marginBottom: 'var(--space-5)',
        color: 'var(--text-primary)',
    },
    summarySticky: { position: 'sticky' as const, top: 'var(--space-5)' },
    // Fields
    field: { display: 'flex', flexDirection: 'column', gap: 'var(--space-2)', marginBottom: 'var(--space-4)' },
    label: { fontSize: 'var(--text-sm)', fontWeight: 'var(--font-medium)', color: 'var(--text-primary)' },
    input: {
        height: 42,
        padding: '0 var(--space-4)',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--radius-lg)',
        background: 'var(--bg-primary)',
        fontSize: 'var(--text-sm)',
        color: 'var(--text-primary)',
        width: '100%',
    },
    inputErr: {
        height: 42,
        padding: '0 var(--space-4)',
        border: '1px solid var(--color-error)',
        borderRadius: 'var(--radius-lg)',
        background: 'var(--bg-primary)',
        fontSize: 'var(--text-sm)',
        color: 'var(--text-primary)',
        width: '100%',
    },
    select: {
        height: 42,
        padding: '0 var(--space-4)',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--radius-lg)',
        background: 'var(--bg-primary)',
        fontSize: 'var(--text-sm)',
        color: 'var(--text-primary)',
        width: '100%',
        cursor: 'pointer',
    },
    selectErr: {
        height: 42,
        padding: '0 var(--space-4)',
        border: '1px solid var(--color-error)',
        borderRadius: 'var(--radius-lg)',
        background: '#fef2f2',
        fontSize: 'var(--text-sm)',
        color: 'var(--text-primary)',
        width: '100%',
        cursor: 'pointer',
    },
    textarea: {
        padding: 'var(--space-3) var(--space-4)',
        border: '1px solid var(--border-color)',
        borderRadius: 'var(--radius-lg)',
        background: 'var(--bg-primary)',
        fontSize: 'var(--text-sm)',
        color: 'var(--text-primary)',
        width: '100%',
        minHeight: 80,
        resize: 'vertical' as const,
    },
    // Hints
    hint: { fontSize: 'var(--text-xs)', color: 'var(--text-tertiary)', marginTop: 2 },
    hintOk: {
        fontSize: 'var(--text-xs)',
        color: 'var(--color-success)',
        marginTop: 2,
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-1)',
    },
    hintErr: {
        fontSize: 'var(--text-xs)',
        color: 'var(--color-error)',
        marginTop: 2,
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-1)',
    },
    // Banners
    bannerErr: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 'var(--space-3)',
        padding: 'var(--space-3) var(--space-4)',
        background: '#fef2f2',
        border: '1px solid #fecaca',
        borderRadius: 'var(--radius-lg)',
        marginBottom: 'var(--space-4)',
        fontSize: 'var(--text-sm)',
        color: '#dc2626',
    },
    bannerWarn: {
        display: 'flex',
        alignItems: 'flex-start',
        gap: 'var(--space-3)',
        padding: 'var(--space-3) var(--space-4)',
        background: '#fffbeb',
        border: '1px solid #fde68a',
        borderRadius: 'var(--radius-lg)',
        marginBottom: 'var(--space-4)',
        fontSize: 'var(--text-sm)',
        color: '#92400e',
    },
    // Summary rows
    summaryRow: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: 'var(--space-3) 0',
        borderBottom: '1px solid var(--border-color)',
        fontSize: 'var(--text-sm)',
    },
    summaryLabel: { color: 'var(--text-tertiary)' },
    summaryValue: { fontWeight: 'var(--font-medium)', color: 'var(--text-primary)' },
    totalRow: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: 'var(--space-4) 0',
        fontSize: 'var(--text-lg)',
        fontWeight: 'var(--font-bold)',
        marginTop: 'var(--space-2)',
    },
    // Buttons
    btnPrimary: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 'var(--space-2)',
        padding: 'var(--space-3)',
        background: 'var(--color-primary-500)',
        color: 'white',
        borderRadius: 'var(--radius-lg)',
        fontSize: 'var(--text-sm)',
        fontWeight: 'var(--font-semibold)',
        width: '100%',
        marginTop: 'var(--space-4)',
        cursor: 'pointer',
        border: 'none',
    },
    btnOutline: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 'var(--space-2)',
        padding: 'var(--space-3)',
        background: 'transparent',
        border: '1px dashed var(--color-primary-500)',
        color: 'var(--color-primary-500)',
        borderRadius: 'var(--radius-lg)',
        fontSize: 'var(--text-sm)',
        fontWeight: 'var(--font-semibold)',
        width: '100%',
        cursor: 'pointer',
    },
    btnGhost: {
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        color: 'var(--text-secondary)',
        fontSize: 'var(--text-sm)',
    },
    btnCollapse: {
        background: 'none',
        border: 'none',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-1)',
        color: 'var(--color-primary-500)',
        fontSize: 'var(--text-xs)',
        fontWeight: 'var(--font-medium)',
        marginTop: 'var(--space-2)',
        padding: 0,
    },
    // Misc
    badge: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 'var(--space-1)',
        padding: '2px 8px',
        borderRadius: 'var(--radius-full)',
        fontSize: 'var(--text-xs)',
        fontWeight: 'var(--font-medium)',
    },
    dot: { width: 10, height: 10, borderRadius: '50%', flexShrink: 0, marginTop: 2 },
    divider: { borderTop: '1px dashed var(--border-color)', margin: 'var(--space-4) 0', paddingTop: 'var(--space-4)' },
    availRow: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 'var(--space-2) 0',
        borderBottom: '1px dashed var(--border-color)',
        fontSize: 'var(--text-xs)',
    },
    condGrid: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr 1fr',
        gap: 'var(--space-2)',
        marginTop: 'var(--space-2)',
    },
    painTrack: { display: 'flex', gap: 'var(--space-1)', marginTop: 'var(--space-2)', flexWrap: 'wrap' as const },
    searchWrap: { position: 'relative' as const, marginBottom: 'var(--space-4)' },
    searchIcon: {
        position: 'absolute' as const,
        insetInlineStart: 'var(--space-3)',
        top: '50%',
        transform: 'translateY(-50%)',
        color: 'var(--text-tertiary)',
    },
    checkRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 'var(--space-2)',
        marginBottom: 'var(--space-2)',
        cursor: 'pointer',
    },
    checkLabel: { fontSize: 'var(--text-sm)', color: 'var(--text-primary)', cursor: 'pointer' },
};
